kind: pipeline
name: build-and-test-amd64

platform:
  arch: amd64

steps:
- name: Build
  image: gcc
  commands:
  - apt install g++-7 libboost-all-dev cmake-data cmake
  - cmake .
  - make
  - ./ket_jm 1 3/2 
