kind: pipeline
name: build-and-test-amd64

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
commands:
  - apt-get update -y
  - apt-get install -y make gcc g++ cmake perl boost 
  - cmake .
  - make
  - ./ket_jm 1 3/2
